name: Pull Request
on: pull_request
jobs:
  commit_check:
    name: Conventional Commits Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Check Commits
        uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pull_request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn prisma generate
      - name: Tests
        run: yarn test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn test
